server:
  port: 8086
logging:
  level:
    com.pxf.count.*: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/counting
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
